export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USER_BY_ID_PENDING = 'FETCH_USER_BY_ID_PENDING';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_ERROR = 'FETCH_USER_BY_ID_ERROR';

export const SET_USER_EMAIL_PENDING = 'SET_USER_EMAIL_PENDING';
export const SET_USER_EMAIL_SUCCESS = 'SET_USER_EMAIL_SUCCESS';
export const SET_USER_EMAIL_ERROR = 'SET_USER_EMAIL_ERROR';

export const SET_USER_LOCALE = 'SET_USER_LOCALE';

export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const HANDLE_ADMIN_PERMISSIONS_PENDING = 'HANDLE_ADMIN_PERMISSIONS_PENDING';
export const HANDLE_ADMIN_PERMISSIONS_SUCCESS = 'HANDLE_ADMIN_PERMISSIONS_SUCCESS';
export const HANDLE_ADMIN_PERMISSIONS_ERROR = 'HANDLE_ADMIN_PERMISSIONS_ERROR';

export const FETCH_USER_NOTIFICATIONS_PENDING = 'FETCH_USER_NOTIFICATIONS_PENDING';
export const FETCH_USER_NOTIFICATIONS_SUCCESS = 'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_ERROR = 'FETCH_USER_NOTIFICATIONS_ERROR';

export const DELETE_USER_NOTIFICATION_PENDING = 'DELETE_USER_NOTIFICATION_PENDING';
export const DELETE_USER_NOTIFICATION_SUCCESS = 'DELETE_USER_NOTIFICATION_SUCCESS';
export const DELETE_USER_NOTIFICATION_ERROR = 'DELETE_USER_NOTIFICATION_ERROR';

export const SET_USER_NOTIFICATIONS_PENDING = 'SET_USER_NOTIFICATIONS_PENDING';
export const SET_USER_NOTIFICATIONS_SUCCESS = 'SET_USER_NOTIFICATIONS_SUCCESS';
export const SET_USER_NOTIFICATIONS_ERROR = 'SET_USER_NOTIFICATIONS_ERROR';

export const CHECK_USER_NOTIFICATIONS_PENDING = 'CHECK_USER_NOTIFICATIONS_PENDING';
export const CHECK_USER_NOTIFICATIONS_SUCCESS = 'CHECK_USER_NOTIFICATIONS_SUCCESS';
export const CHECK_USER_NOTIFICATIONS_ERROR = 'CHECK_USER_NOTIFICATIONS_ERROR';
