export const FETCH_LINKS_PENDING = 'FETCH_LINKS_PENDING';
export const FETCH_LINKS_SUCCESS = 'FETCH_LINKS_SUCCESS';
export const FETCH_LINKS_ERROR = 'FETCH_LINKS_ERROR';

export const ADD_LINK_STARTED = 'ADD_LINK_STARTED';
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE';

export const DELETE_LINK_STARTED = 'DELETE_LINK_STARTED';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';
