export const FETCH_STUDIES_MAJOR_PENDING = 'FETCH_STUDIES_MAJOR_PENDING';
export const FETCH_STUDIES_MAJOR_SUCCESS = 'FETCH_STUDIES_MAJOR_SUCCESS';
export const FETCH_STUDIES_MAJOR_ERROR = 'FETCH_STUDIES_MAJOR_ERROR';