export const FETCH_TUTOR_DEGREE_PENDING = 'FETCH_TUTOR_DEGREE_PENDING';
export const FETCH_TUTOR_DEGREE_SUCCESS = 'FETCH_TUTOR_DEGREE_SUCCESS';
export const FETCH_TUTOR_DEGREE_ERROR = 'FETCH_TUTOR_DEGREE_ERROR';