export const FETCH_POST_COMMENTS_PENDING = 'FETCH_POST_COMMENTS_PENDING';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const ADD_COMMENT_STARTED = 'ADD_COMMENT_STARTED';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const COMMENT_LIKE_REQUEST = 'COMMENT_LIKE_REQUEST';
export const COMMENT_LIKE_SUCCESS = 'COMMENT_LIKE_SUCCESS';
export const COMMENT_LIKE_FAILURE = 'COMMENT_LIKE_FAILURE';

export const ACCEPT_ANSWER_REQUEST = 'ACCEPT_ANSWER_REQUEST';
export const ACCEPT_ANSWER_SUCCESS = 'ACCEPT_ANSWER_SUCCESS';
export const ACCEPT_ANSWER_FAILURE = 'ACCEPT_ANSWER_FAILURE';

export const EDIT_COMMENT_STARTED = 'EDIT_COMMENT_STARTED';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

export const DELETE_COMMENT_STARTED = 'DELETE_COMMENT_STARTED';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const CHANGE_COMMENT_SIZE = 'CHANGE_COMMENT_SIZE';
