export const FETCH_TUTORING_OFFERS_PENDING = 'FETCH_TUTORING_OFFERS_PENDING';
export const FETCH_TUTORING_OFFERS_SUCCESS = 'FETCH_TUTORING_OFFERS_SUCCESS';
export const FETCH_TUTORING_OFFERS_ERROR = 'FETCH_TUTORING_OFFERS_ERROR';

export const ADD_TUTORING_OFFER_STARTED = 'ADD_TUTORING_OFFER_STARTED';
export const ADD_TUTORING_OFFER_SUCCESS = 'ADD_TUTORING_OFFER_SUCCESS';
export const ADD_TUTORING_OFFER_FAILURE = 'ADD_TUTORING_OFFER_FAILURE';

export const EDIT_TUTORING_OFFER_STARTED = 'EDIT_TUTORING_OFFER_STARTED';
export const EDIT_TUTORING_OFFER_SUCCESS = 'EDIT_TUTORING_OFFER_SUCCESS';
export const EDIT_TUTORING_OFFER_FAILURE = 'EDIT_TUTORING_OFFER_FAILURE';

export const DELETE_TUTORING_OFFER_STARTED = 'DELETE_TUTORING_OFFER_STARTED';
export const DELETE_TUTORING_OFFER_SUCCESS = 'DELETE_TUTORING_OFFER_SUCCESS';
export const DELETE_TUTORING_OFFER_FAILURE = 'DELETE_TUTORING_OFFER_FAILURE';

export const OFFER_INTEREST_PENDING = 'OFFER_INTEREST_PENDING';
export const OFFER_INTEREST_SUCCESS = 'OFFER_INTEREST_SUCCESS';
export const OFFER_INTEREST_ERROR = 'OFFER_INTEREST_ERROR';

export const FETCH_IS_USER_INTERESTED_PENDING = 'FETCH_IS_USER_INTERESTED_PENDING';
export const FETCH_IS_USER_INTERESTED_SUCCESS = 'FETCH_IS_USER_INTERESTED_SUCCESS';
export const FETCH_IS_USER_INTERESTED_ERROR = 'FETCH_IS_USER_INTERESTED_ERROR';