export const FETCH_NOTICES_PENDING = 'FETCH_NOTICES_PENDING';
export const FETCH_NOTICES_SUCCESS = 'FETCH_NOTICES_SUCCESS';
export const FETCH_NOTICES_ERROR = 'FETCH_NOTICES_ERROR';

export const ADD_NOTICE_STARTED = 'ADD_NOTICE_STARTED';
export const ADD_NOTICE_SUCCESS = 'ADD_NOTICE_SUCCESS';
export const ADD_NOTICE_FAILURE = 'ADD_NOTICE_FAILURE';

export const EDIT_NOTICE_STARTED = 'EDIT_NOTICE_STARTED';
export const EDIT_NOTICE_SUCCESS = 'EDIT_NOTICE_SUCCESS';
export const EDIT_NOTICE_FAILURE = 'EDIT_NOTICE_FAILURE';

export const DELETE_NOTICE_STARTED = 'DELETE_NOTICE_STARTED';
export const DELETE_NOTICE_SUCCESS = 'DELETE_NOTICE_SUCCESS';
export const DELETE_NOTICE_FAILURE = 'DELETE_NOTICE_FAILURE';
