export const SEND_FIREBASE_TOKEN_PENDING = 'SEND_FIREBASE_TOKEN_PENDING';
export const SEND_FIREBASE_TOKEN_SUCCESS = 'SEND_FIREBASE_TOKEN_SUCCESS';
export const SEND_FIREBASE_TOKEN_ERROR = 'SEND_FIREBASE_TOKEN_ERROR';
