export const FETCH_COURSES_PENDING = 'FETCH_COURSES_PENDING';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR';

export const FETCH_COURSE_PENDING = 'FETCH_COURSE_PENDING';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_ERROR = 'FETCH_COURSE_ERROR';

export const FETCH_USER_COURSES_PENDING = 'FETCH_USER_COURSES_PENDING';
export const FETCH_USER_COURSES_SUCCESS = 'FETCH_USER_COURSES_SUCCESS';
export const FETCH_USER_COURSES_ERROR = 'FETCH_USER_COURSES_ERROR';

export const DELETE_COURSE_STARTED = 'DELETE_COURSE_STARTED';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';

export const ADD_COURSE_STARTED = 'ADD_COURSE_STARTED';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';

export const EDIT_COURSE_STARTED = 'EDIT_COURSE_STARTED';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';

export const FETCH_COURSE_USERS_STARTED = 'FETCH_COURSE_USERS_STARTED';
export const FETCH_COURSE_USERS_SUCCESS = 'FETCH_COURSE_USERS_SUCCESS';
export const FETCH_COURSE_USERS_FAILURE = 'FETCH_COURSE_USERS_FAILURE';

export const JOIN_COURSE_STARTED = 'JOIN_COURSE_STARTED';
export const JOIN_COURSE_SUCCESS = 'JOIN_COURSE_SUCCESS';
export const JOIN_COURSE_FAILURE = 'JOIN_COURSE_FAILURE';

export const LEAVE_COURSE_STARTED = 'LEAVE_COURSE_STARTED';
export const LEAVE_COURSE_SUCCESS = 'LEAVE_COURSE_SUCCESS';
export const LEAVE_COURSE_FAILURE = 'LEAVE_COURSE_FAILURE';
