export const FETCH_TUTOR_PENDING = 'FETCH_TUTOR_PENDING';
export const FETCH_TUTOR_SUCCESS = 'FETCH_TUTOR_SUCCESS';
export const FETCH_TUTOR_ERROR = 'FETCH_TUTOR_ERROR';

export const FETCH_TUTOR_COURSES_PENDING = 'FETCH_TUTOR_COURSES_PENDING';
export const FETCH_TUTOR_COURSES_SUCCESS = 'FETCH_TUTOR_COURSES_SUCCESS';
export const FETCH_TUTOR_COURSES_ERROR = 'FETCH_TUTOR_COURSES_ERROR';

export const ADD_TUTOR_STARTED = 'ADD_TUTOR_STARTED';
export const ADD_TUTOR_SUCCESS = 'ADD_TUTOR_SUCCESS';
export const ADD_TUTOR_FAILURE = 'ADD_TUTOR_FAILURE';

export const DELETE_TUTOR_STARTED = 'DELETE_TUTOR_STARTED';
export const DELETE_TUTOR_SUCCESS = 'DELETE_TUTOR_SUCCESS';
export const DELETE_TUTOR_FAILURE = 'DELETE_TUTOR_FAILURE';

export const EDIT_TUTOR_STARTED = 'EDIT_TUTOR_STARTED';
export const EDIT_TUTOR_SUCCESS = 'EDIT_TUTOR_SUCCESS';
export const EDIT_TUTOR_FAILURE = 'EDIT_TUTOR_FAILURE';
