export const GET_FILES_LIST_PENDING = 'GET_FILES_LIST_PENDING';
export const GET_FILES_LIST_SUCCESS = 'GET_FILES_LIST_SUCCESS';
export const GET_FILES_LIST_FAILURE = 'GET_FILES_LIST_FAILURE';

export const GET_FILE_PENDING = 'GET_FILE_PENDING';
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS';
export const GET_FILE_FAILURE = 'GET_FILE_FAILURE';

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

export const DELETE_FILE_PENDING = 'DELETE_FILE_PENDING';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';
